/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package re.notifica;

public final class R {
	public static final class id {
		public static final int list = 0x7f060040;
		public static final int message = 0x7f06003f;
		public static final int notificare_callback_image = 0x7f060041;
		public static final int notificare_callback_message = 0x7f060043;
		public static final int notificare_send_button = 0x7f060042;
		public static final int notification_fragment = 0x7f060044;
	}
	public static final class layout {
		public static final int notificare_alert_dialog = 0x7f030018;
		public static final int notificare_callback_camera = 0x7f030019;
		public static final int notificare_callback_camera_keyboard = 0x7f03001a;
		public static final int notificare_callback_keyboard = 0x7f03001b;
		public static final int notificare_notification_container = 0x7f03001c;
		public static final int notificare_notification_fragment = 0x7f03001d;
	}
	public static final class string {
		public static final int notificare_action_error_no_dialer = 0x7f0b002f;
		public static final int notificare_action_error_no_email_clients = 0x7f0b002d;
		public static final int notificare_action_error_no_sms_clients = 0x7f0b002e;
		public static final int notificare_action_failed = 0x7f0b0032;
		public static final int notificare_action_progress = 0x7f0b0030;
		public static final int notificare_action_success = 0x7f0b0031;
		public static final int notificare_action_title_intent_email = 0x7f0b002a;
		public static final int notificare_action_title_intent_sms = 0x7f0b002b;
		public static final int notificare_action_title_intent_telephone = 0x7f0b002c;
		public static final int notificare_notification_error_gms_connect = 0x7f0b0029;
		public static final int notificare_notification_has_action = 0x7f0b0028;
		public static final int notificare_text_back = 0x7f0b0035;
		public static final int notificare_text_cancel = 0x7f0b0034;
		public static final int notificare_text_message_hint = 0x7f0b0036;
		public static final int notificare_text_send = 0x7f0b0033;
	}
}
